### ISSUE TITLE
Add settings for cookie path and expires

### ISSUE THREAD

**Issue by ghost** [harborhoffer/Super-Theme-Switcher#2]
It would be helpful if there were settings for the cookie path and expires options. By adding this modification to your code, user would be able to support themes across an entire site with potentially no expire time. In my local copy of your JavaScript I have modified the code like this:

```
    var settings = {
        // ... all the preceding options ...
        cookieexpires: 365,
        cookiepath: '/'
    };
```

Then in the updateTheme function change the code to use those new options like this:

```
    function updateTheme(data) {
        // ... All the preceding code ...

        $.cookie(settings.cookiename, data.name, 
            { expires: settings.cookieexpires, path: settings.cookiepath });

        // ... some other code was here ...
    }
```

**Important note:**
In order for this to work you will have to bring in the latest version of the embedded [cookie plugin](https://github.com/carhartl/jquery-cookie) because they added support for expires.

**Comment by harborhoffer** [comment]
Thank you. Plugin is updated.
