### ISSUE TITLE
Problem with jquery ui 1.8.23

### ISSUE THREAD

**Issue by ghost** [harborhoffer/Super-Theme-Switcher#4]
I upgraded jquery to the most recent version and I'm getting an error from super-theme-switcher.

Uncaught Error: Syntax error, unrecognized expression: 
[@rel^=style][href^="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/"]

**Comment by ghost** [comment]
It works when I change the selector to this:

currentStyle = $('link[href^="' + urlPrefix + '"]').first();

**Comment by pulzpulz** [comment]
http://api.jquery.com/category/selectors/

Quote from:

"If you wish to use any of the meta-characters ( such as !"#$%&'()*+,./:;<=>?@[]^`{|}~ ) as a literal part of a name, you must escape the character with two backslashes: \."
i escaped the @ and everithing is ok!

currentStyle = $('link[\@rel^=style][href^="'+urlPrefix+'"]').first();     

jquery 1.8.1 , jquery ui 1.8.23

**Comment by harborhoffer** [comment]
Thank you. I made this change in the commit below.
https://github.com/harborhoffer/Super-Theme-Switcher/commit/5a800e74d5804f9a999b583a2473893fbd9d8094

**Comment by leniel** [comment]
Interesting: this very error is still present in the latest version:

```
Error: Syntax error, unrecognized expression: link[@rel^=style][href^="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/"]
[Break On This Error]   

throw new Error( "Syntax error, unrecognized expression: " + msg );
```

If I do as shown by @alforno everything works great! So I think the patch should be:

```
currentStyle = $('link[href^="' + urlPrefix + '"]').first();
```
