### ISSUE TITLE
Crash with jquery 1.8

### ISSUE THREAD

**Issue by BrendonOSullivan** [harborhoffer/Super-Theme-Switcher#5]
I tried to use the Super-Theme-Switcher with jquery 1.8

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>

but this causes a crash in Sizzle:

```
Error: Syntax error, unrecognized expression: link[@rel^=style][href^="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.10/themes/"]
```

The error breaks everything in Jquery so it's a real show-stopper. It doesn't happen in Jquery 1.7 and earlier.

Doing some debugging shows the error occurs in this line (function updateTheme):
     currentStyle = $('link[\@rel^=style][href^="'+urlPrefix+'"]').first();

I changed this line as follows and then everything worked ok for me. 
    currentStyle = $('link[href^="'+urlPrefix+'"]').first();

It even still works on jquery 1.7 so maybe the directive "[\@rel^=style]" is unnecessary?

**Comment by harborhoffer** [comment]
Thank you. the "[\@rel^=style]" directive is definitely not needed. I have committed the fix.

**Comment by BrendonOSullivan** [comment]
Hey, wow. Thanks for the fast response. It works now with the standard js script.

There is something wrong with the minimized version though. It throws out an error in Firebug:
    TypeError: c.B is undefined

That's impossible to debug. Maybe you can just remake the minimised version?

**Comment by harborhoffer** [comment]
Woops. Fixed now in the latest commit.

**Comment by BrendonOSullivan** [comment]
I confirm that it works now in both the inflated and minimised version.
Thanks a bunch.
